### ISSUE TITLE
trouble with compiling using arm gcc 7

### ISSUE THREAD

**Issue by Rb37** [m-peko/bitflags#18]
Hi!
I really interested in this library, and I want to use it in my project for embedded systems.
Unfortunately it doesn't compile using arm-none-eabi-gcc 7.2.1.
Here's a link.
https://godbolt.org/z/jEv8xY
Thanks in advance.

**Comment by m-peko** [comment]
Hi @Rb37,

I am glad you like this library. I will take a look at this and try to make it compile ASAP.
Will keep you informed about the status.

Thanks

**Comment by m-peko** [comment]
It compiles just fine for me. Take a look at it https://godbolt.org/z/8nG83j.
Maybe you are not using the latest version.

**Comment by Rb37** [comment]
It does not compile if you don't include iostream first
https://godbolt.org/z/q5zox8

Update: 
I figure it out. Its just a missing header. Everything work fine if before including bitflags I include <utility>.
It probably should be included inside a library.

**Comment by m-peko** [comment]
You are right. `utility` header is needed.
